name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Run tests
        run: npm test

      - name: Run tests with coverage
        run: npm run test:ci
        if: matrix.node-version == '24.x'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.node-version == '24.x'
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build project
        run: npm run build

      - name: Test CLI installation
        run: |
          npm link
          call-structure --version
          call-structure --help

      - name: Run CLI smoke tests
        run: |
          # Test basic functionality
          call-structure analyze --entry "examples/simple-project/src/main.ts#main" --output test-output.json
          if [ ! -f "test-output.json" ]; then
            echo "CLI smoke test failed: output file not created"
            exit 1
          fi
          echo "CLI smoke test passed"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: matrix.node-version == '24.x'
        with:
          name: build-artifacts
          path: |
            dist/
            package.json
            README.md
          retention-days: 7

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate

      - name: Run security scan
        run: |
          # Check for potential security issues in dependencies
          npx audit-ci --moderate
        continue-on-error: true
